# Tính năng bán
sell:
  enable: true
  # Giá của mỗi loại
  price:
    STONE: 1
    DIAMOND: 5.5

# Chế độ lưu trữ
# Mặc định: file, có thể lưu MySQL
storage:
  file:
    enable: true
  mysql:
    database:
      host: localhost
      port: 3306
      name: rpg
      user: root
      password: ''

# Số lượng ore tối đa mỗi loại mà player có thể cất vào /kho (mặc định là 256)
# Số lượng phải chia chết cho 64
max-default: 256

# Permission cho player lưu trữ quặng (tối đa 64000)
max-permission: 'blockstorage.{value}'

# Các world cho phép xài tính năng /kho
worlds:
  - world_skyblock
  - world_skyblock_nether

# Menu /kho
gui-size: 9
gui-title: '&c&lKHO QUẶNG'
# Cách bố trí GUI
gui:
  '0':
    type: COBBLESTONE
    # Số lượng lấy ra của các click
    # Chuột giữa = cất hết
    right-click: 1
    left-click: 16
    shift-left-click: 64
    shift-right-click: 256
  '1':
    type: COAL
    right-click: 1
    left-click: 16
    shift-left-click: 64
    shift-right-click: 256
  '2':
    type: REDSTONE
    right-click: 1
    left-click: 16
    shift-left-click: 64
    shift-right-click: 256
  '3':
    # Đây là LAPIS_LAZULI
    # 1.12 trở xuống không có LAPIS, phải ghi là INK_SACK
    # api 1.12 ngu như chó
    type: INK_SACK
    right-click: 1
    left-click: 16
    shift-left-click: 64
    shift-right-click: 256
  '4':
    type: IRON_INGOT
    right-click: 1
    left-click: 16
    shift-left-click: 64
    shift-right-click: 256
  '5':
    type: GOLD_INGOT
    right-click: 1
    left-click: 16
    shift-left-click: 64
    shift-right-click: 256
  '6':
    type: DIAMOND
    right-click: 1
    left-click: 16
    shift-left-click: 64
    shift-right-click: 256
  '7':
    type: EMERALD
    right-click: 1
    left-click: 16
    shift-left-click: 64
    shift-right-click: 256

# Các cài đặt
option:
  # Có tự động match kiểu IRON_INGOT thành IRON_BLOCK hay không
  # Khuyên: không nên bật cái này
  auto-match: false
  match:
    IRON_INGOT: IRON_BLOCK
    GOLD_INGOT: GOLD_BLOCK
  # Khi phá block thì sẽ được cái gì
  # STONE được COBBLESTONE
  # COAL_ORE được COAL
  replace:
    STONE: COBBLESTONE
    COAL_ORE: COAL
    REDSTONE_ORE: REDSTONE
    LAPIS_ORE: INK_SACK
    IRON_ORE: IRON_INGOT
    GOLD_ORE: GOLD_INGOT
    DIAMOND_ORE: DIAMOND
    EMERALD_ORE: EMERALD
    GLOWING_REDSTONE_ORE: REDSTONE

  # Những block cho phép phá để vào /kho
  allow-block:
    - COBBLESTONE
    - COAL_ORE
    - REDSTONE_ORE
    - LAPIS_ORE
    - IRON_ORE
    - GOLD_ORE
    - DIAMOND_ORE
    - EMERALD_ORE
    - GLOWING_REDSTONE_ORE

  # Những block cho phép áp dụng tính phù phép Gia tài
  loot-bonus-block:
    - COBBLESTONE
    - COAL
    - REDSTONE
    - LAPIS_LAZULI
    - INK_SACK
    - IRON_INGOT
    - GOLD_INGOT
    - DIAMOND
    - EMERALD
